name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install required gems
        run: gem install gem-release

      - name: bump gem version
        run: |
          # bump gem version
          git config user.name    "ci system"
          git config user.email   "noreply@kbase.pw"

          commits_request="git log $(git describe --tags --abbrev=0)..HEAD --oneline"
          if [[ $(eval "${commits_request}" | wc -l) -eq 0 ]]
          then
            echo "no new commits found!"
          else
            if [[ $(eval "${commits_request}" | grep "BREAKING CHANGE" | wc -l) -gt 0 ]]
            then
              bump_level=major
            else
              if [[ $(eval "${commits_request}" | grep -E "feat(\(.*?\))?:" | wc -l) -gt 0 ]]
              then
                bump_level=minor
              else
                bump_level=patch
              fi
            fi

            echo "version bump $bump_level"
            eval "${commits_request}"
            echo ""
            gem bump --version $bump_level --skip-ci --push --tag
          fi

      - name: publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ":github: Bearer $GITHUB_TOKEN" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem release --host https://rubygems.pkg.github.com/kbasepw --key github

